using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace mpGen
{
    class header
    {
        public header()
        {
            id = 0x10001;
            name = "Unnamed";
            datum = "W84";
            treSize = 1000;//1000-10000
            rgnLimit = 1024;
            preProcess = "F";
            level = new Dictionary<ushort, ushort>();
            level[0] = 23;
            level[1] = 22;
            zoom = new Dictionary<ushort, ushort>();
            //zoom[0] = 0;
            //zoom[1] = 1;
        }
        public UInt32 id;
        public String name;
        public String datum;
        public UInt32 treSize;
        public UInt16 rgnLimit;
        public String preProcess;
        public Dictionary<UInt16, UInt16> level;
        public Dictionary<UInt16, UInt16> zoom;
        public override string ToString()
        {
            var s = ";Generated by A77X7 mpGen" + mpFile.lineSeparator;
            s += "[IMG ID]" + mpFile.lineSeparator;
            s += "ID=" + id.ToString() + mpFile.lineSeparator;
            if (name != null)
                s += "Name=" + name + mpFile.lineSeparator;
            if (datum != null)
                s += "Datum=" + datum + mpFile.lineSeparator;
            s += "TreSize=" + treSize.ToString() + mpFile.lineSeparator;
            s += "RgnLimit=" + rgnLimit.ToString() + mpFile.lineSeparator;
            if (preProcess != null)
                s += "PreProcess=" + preProcess + mpFile.lineSeparator;
            if (level.Count > 0)
                s += "Levels=" + level.Count.ToString() + mpFile.lineSeparator;
            foreach (var pair in level)
            {
                s += "Level" + pair.Key.ToString() + "=" + pair.Value.ToString() + mpFile.lineSeparator;
            }
            foreach (var pair in zoom)
            {
                s += "Zoom" + pair.Key.ToString() + "=" + pair.Value.ToString() + mpFile.lineSeparator;
            }
            s += "[END]" + mpFile.lineSeparator;
            return s;
        }
    }
}
